[development]
address = "0.0.0.0"
port = 8000
workers = 8
log = "normal"
secret_key = "xjT6vC+7XUtzvreMJ2jroK1bqUqOR8/VNh62rp7XEXs="
limits = { forms = 32768 }

#[global.tls]
#certs = "./certstore/certs.pem"
#key = "./certstore/key.pem"
