npx:
	npx babel --watch src --out-dir . --presets react-app/prod

setup:
	npm init -y
	npm install babel-cli@6 babel-preset-react-app@3
	wget https://github.com/twbs/bootstrap/releases/download/v4.5.0/bootstrap-4.5.0-dist.zip
	unzip bootstrap-4.5.0-dist.zip
